# Generated by Django 5.0.2 on 2024-03-06 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnosis', '0002_diagnosisparameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosis',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
