# Generated by Django 5.0.2 on 2024-03-06 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0002_alter_bill_item'),
        ('diagnosis', '0003_diagnosis_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiagnosisPrice',
        ),
    ]
