# Generated by Django 5.0.2 on 2024-03-16 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_alter_patientreportdetails_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdiagnosis',
            name='isChecked',
            field=models.BooleanField(default=False),
        ),
    ]
